### ISSUE TITLE
qué es action="#" y method="post"??

### ISSUE THREAD

**Issue by ManuMoroncini** [nikosff/JavaScriptVilladaEjercicios#3]
https://github.com/nikosff/JavaScriptVilladaEjercicios/blob/47c2d28b057af16571a5f846d48376ec0702a27d/5_GenerarTickets/index.html#L12

**Comment by FranciscodeMaussion** [comment]
El action va a ser a donde va a redirigir la informacion del form, y el method tiene que ver con como lo va a enviar. Cuando nosotros recargamos una pagina estamos haciendo un GET, cuando enviamos infomracion por lo general un POST. Igual no es importante por ahora.

**Comment by nicolasfanin** [comment]
@ManuMoroncini ahi esta la respuesta!
